version: '3.7'

services:
  postgres_postgis_parser:
    image: postgis/postgis
    container_name: postgres_postgis_parser
    restart: always
    volumes:
      - postgres_data_parser:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

  redis_parser:
    image: redis:latest
    container_name: redis_parser
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - custom_network

  adminer_pgadmin4_parser:
    image: dpage/pgadmin4
    container_name: adminer_pgadmin4_parser
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8095:80
    volumes:
      - pgadmin_data_parser:/var/lib/pgadmin
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  hotel-parser-1:
    build: ./ 
    container_name: hotel-parser-1
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_1}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_1}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_1}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_1}
      PROXY_PORT: ${PROXY_PORT_1}
      PROXY_LOGIN: ${PROXY_LOGIN_1}
      PROXY_PASSWORD: ${PROXY_PASSWORD_1}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always # эта строка добавляет автоматический перезапуск

  hotel-parser-2:
    build: ./ 
    container_name: hotel-parser-2
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_2}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_2}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_2}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_2}
      PROXY_PORT: ${PROXY_PORT_2}
      PROXY_LOGIN: ${PROXY_LOGIN_2}
      PROXY_PASSWORD: ${PROXY_PASSWORD_2}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-3:
    build: ./ 
    container_name: hotel-parser-3
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_3}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_3}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_3}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_3}
      PROXY_PORT: ${PROXY_PORT_3}
      PROXY_LOGIN: ${PROXY_LOGIN_3}
      PROXY_PASSWORD: ${PROXY_PASSWORD_3}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-4:
    build: ./ 
    container_name: hotel-parser-4
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_4}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_4}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_4}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_4}
      PROXY_PORT: ${PROXY_PORT_4}
      PROXY_LOGIN: ${PROXY_LOGIN_4}
      PROXY_PASSWORD: ${PROXY_PASSWORD_4}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-5:
    build: ./ 
    container_name: hotel-parser-5
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_5}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_5}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_5}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_5}
      PROXY_PORT: ${PROXY_PORT_5}
      PROXY_LOGIN: ${PROXY_LOGIN_5}
      PROXY_PASSWORD: ${PROXY_PASSWORD_5}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-6:
    build: ./ 
    container_name: hotel-parser-6
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_6}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_6}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_6}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_6}
      PROXY_PORT: ${PROXY_PORT_6}
      PROXY_LOGIN: ${PROXY_LOGIN_6}
      PROXY_PASSWORD: ${PROXY_PASSWORD_6}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-7:
    build: ./ 
    container_name: hotel-parser-7
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_7}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_7}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_7}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_7}
      PROXY_PORT: ${PROXY_PORT_7}
      PROXY_LOGIN: ${PROXY_LOGIN_7}
      PROXY_PASSWORD: ${PROXY_PASSWORD_7}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-8:
    build: ./ 
    container_name: hotel-parser-8
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_8}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_8}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_8}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_8}
      PROXY_PORT: ${PROXY_PORT_8}
      PROXY_LOGIN: ${PROXY_LOGIN_8}
      PROXY_PASSWORD: ${PROXY_PASSWORD_8}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-9:
    build: ./ 
    container_name: hotel-parser-9
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_9}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_9}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_9}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_9}
      PROXY_PORT: ${PROXY_PORT_9}
      PROXY_LOGIN: ${PROXY_LOGIN_9}
      PROXY_PASSWORD: ${PROXY_PASSWORD_9}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379

    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-11:
    build: ./ 
    container_name: hotel-parser-11
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_11}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_11}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_11}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_11}
      PROXY_PORT: ${PROXY_PORT_11}
      PROXY_LOGIN: ${PROXY_LOGIN_11}
      PROXY_PASSWORD: ${PROXY_PASSWORD_11}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379

    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

  hotel-parser-10:
    build: ./ 
    container_name: hotel-parser-10
    volumes:
      - .:/app
      - /app/node_modules
      - ./logs:/app/logs
      - uploads:/app/uploads
    ports:
      - ${DEV_PORT_10}:3000
    depends_on:
      - postgres_postgis_parser
      - redis_parser
    environment:
      PORT: ${DEV_PORT_10}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      INSTANCE_ID: ${INSTANCE_ID_10}
      TOTAL_INSTANCES: ${TOTAL_INSTANCES}
      PROXY_HOST: ${PROXY_HOST_10}
      PROXY_PORT: ${PROXY_PORT_10}
      PROXY_LOGIN: ${PROXY_LOGIN_10}
      PROXY_PASSWORD: ${PROXY_PASSWORD_10}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_API_URL: ${OPENAI_BASE_API_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}
      YA_FOLDER_ID: ${YA_FOLDER_ID}
      IAM_TOKEN_URL: ${IAM_TOKEN_URL}
      TRANSLATE_API_URL: ${TRANSLATE_API_URL}
      KEY_FILE_PATH: ${KEY_FILE_PATH}
      YA_HTTP_GEOCODER_API_KEY: ${YA_HTTP_GEOCODER_API_KEY}
      AHUNTER_API_KEY: ${AHUNTER_API_KEY}
      REDIS_HOST: redis_parser
      REDIS_PORT: 6379

    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    restart: always

volumes:
  postgres_data_parser:
  pgadmin_data_parser:
  redis_data:
  uploads: 

networks:
  custom_network:
    driver: bridge
