version: "3.9"

services:
  postgres_postgis_parser:
    image: postgis/postgis
    container_name: postgres_postgis_parser
    restart: always
    volumes:
      - postgres_data_parser:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - custom_network

  adminer_pgadmin4_parser:
    image: dpage/pgadmin4
    container_name: adminer_pgadmin4_parser
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8095:80
    volumes:
      - pgadmin_data_parser:/var/lib/pgadmin
    networks:
      - custom_network 

  hotel-parser:
    build: ./ 
    container_name: hotel-parser
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${DEV_PORT}:3000
    depends_on:
      - postgres_postgis_parser
      - 3proxy
    environment:
      PORT: ${DEV_PORT}
      SECRET: ${SECRET}
      IS_DEV: "true"
      BASE_PARSE_URL: ${BASE_PARSE_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    working_dir: /app
    command: sh -c "cd /app; rm -rf dist; npm install; npm run start:dev"
    networks:
      - custom_network

  3proxy:
    build: ./3proxy
    container_name: 3proxy
    ports:
      - "1080:1080"
    networks:
      - custom_network
    environment:
      PROXY_LOGIN: ${PROXY_LOGIN}
      PROXY_PASSWORD: ${PROXY_PASSWORD}

volumes:
  postgres_data_parser:
  pgadmin_data_parser:

networks:
  custom_network:
    driver: bridge
